title: The Top 3 Best Movies of 2019
author: arumakan-akuy
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I personally ranked the best movies of 2019 that you need to watch.  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
